
services:
  backend:
    build: ./backend
    container_name: sports_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app   
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/sportsdb
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: sports_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  frontend:
    build: ./frontend
    container_name: sports_frontend
    ports:
      - "3000:80"   # app runs at http://localhost:3000
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000  # backend URL for API calls


volumes:
  postgres_data:

